### ISSUE TITLE
[PE-D][Tester E] UG help command image is not updated

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-2/tp#134]
UG help command image still refers to AB3 link.

<img src="https://raw.githubusercontent.com/ryanczx/ped/main/files/2216bb0e-de1a-421f-b704-59ebadc2c2c6.png" width=700>

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ryanczx/ped#1

**Comment by kianseong** [comment]
### Proposed Changes
- Update UG with latest help page command.
