### ISSUE TITLE
[PE-D][Tester C] Confusing Error Message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-2/tp#138]
Error messages should be easy to understand. However, this error message can be slightly confusing and the jargons used are unnecessarily technical.

The use of examples of valid inputs might help to make this clearer.

![bug2_confusing error message.png](https://raw.githubusercontent.com/SeekSaveServe/ped/main/files/799bcebc-5260-47d8-8d02-10605ef2b1f7.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: SeekSaveServe/ped#3

**Comment by kianseong** [comment]
### Proposed Changes
- Have a list of error messages in the UG and explain to the user what each error messages mean.
