### ISSUE TITLE
[PE-D][Tester C] Unknown Command tasks

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-2/tp#154]
`tasks [index] is listed in the UG as a viable command but executing it in the app throws "Unknown Command"

![bug 5.png](https://raw.githubusercontent.com/SeekSaveServe/ped/main/files/4d498d5e-21e3-449a-87ea-c3bd8164729c.png)

-------------
Labels: `type.DocumentationBug` `severity.High`
original: SeekSaveServe/ped#6

**Comment by kianseong** [comment]
Fixed.
