### ISSUE TITLE
[PE-D][Tester B] Unmark tasks -- vague description

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T08-2/tp#173]
I am somewhat confused about how I can use the "task unmark" command -- Since all tasks are unmarked upon creation (by default) and a task disappears when marked, how can I unmark a task by its index if I cannot see it from the UI?

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: HakkaNgin/ped#11

**Comment by kianseong** [comment]
## Proposed Changes
- Update task unmark command with needing to run task list -a command before unmarking.
