### ISSUE TITLE
[PE-D][Tester B] Date format for tasks

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T08-2/tp#174]
It would be good to consider date formats for tasks deadlines as well.

![image.png](https://raw.githubusercontent.com/HakkaNgin/ped/main/files/a4c50b25-c332-4f5c-a364-fc302defa272.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: HakkaNgin/ped#12

**Comment by kianseong** [comment]
## Proposed Changes
- Update UG/DG with why we chose this date format.
